var animal_data = [
{'name':'Earth','au':1,'color':'blue','entry':0},
{'name':'Venus','au':0.723,'color':'yellow','entry':0},
{'name':'Mars','au':1.524,'color':'red','entry':0},
{'name':'Mercury','au':0.39,'color':'red','entry':0},

{'name':'Bee (Worker)','life':1},
{'name':'Ant (Worker)','life':2},
{'name':'Mosquitofish','life':2},
{'name':'American Newt','life':3},
{'name':'Anole','life':3},
{'name':'Ant (Queen)','life':3},
{'name':'Fence Lizard','life':4},
{'name':'Golden Hamster','life':4},
{'name':'House Mouse','life':4},
{'name':'Mouse','life':4},
{'name':'Norwegian Rat','life':4},
{'name':'Opossum','life':4},
{'name':'Bee (Queen)','life':5},
{'name':'Gerbil','life':5},
{'name':'Gouldian finch','life':6},
{'name':'Leopard Frog','life':6},
{'name':'Muscrat','life':6},
{'name':'Quail','life':6},
{'name':'Toucan','life':6},
{'name':'Newt','life':7},
{'name':'Red Eared Turtle','life':7},
{'name':'Tasmanian Tiger','life':7},
{'name':'Guinea Pig','life':8},
{'name':'Humming Bird','life':8},
{'name':'Koala','life':8},
{'name':'Mynah','life':8},
{'name':'Kangaroo','life':9},
{'name':'Mudpuppy','life':9},
{'name':'Rabbit','life':9},
{'name':'Cottontail','life':10},
{'name':'Dog, large','life':10},
{'name':'Green Frog','life':10},
{'name':'Grouse','life':10},
{'name':'Hare','life':10},
{'name':'Platypus','life':10},
{'name':'Prarie Dog','life':10},
{'name':'Painted Turtle','life':11},
{'name':'Pigeon','life':11},
{'name':'Tiger Salamander','life':11},
{'name':'Capybara','life':12},
{'name':'Chipmunk','life':12},
{'name':'Ferret','life':12},
{'name':'Mongoose','life':12},
{'name':'Swan','life':12},
{'name':'Civet','life':13},
{'name':'Flying Squirrel','life':14},
{'name':'Fox','life':14},
{'name':'Sea Lion','life':14},
{'name':'Tree Frog','life':14},
{'name':'American Toad','life':15},
{'name':'Angleworm','life':15},
{'name':'Chicken','life':15},
{'name':'Goat','life':15},
{'name':'Grey Cheeked Parrot','life':15},
{'name':'Lobster','life':15},
{'name':'Nutria','life':15},
{'name':'Pionus Parrot','life':15},
{'name':'Rainbow Lorikeet','life':15},
{'name':'Rosella','life':15},
{'name':'Sheep','life':15},
{'name':'South African Clawed Toad','life':15},
{'name':'Whistling Duck','life':15},
{'name':'Wombat','life':15},
{'name':'Woodchuck','life':15},
{'name':'Bull Frog','life':16},
{'name':'Squirrel','life':16},
{'name':'Cicada','life':17},
{'name':'Common Goldeneye','life':17},
{'name':'Leopard','life':17},
{'name':'Redhead Duck','life':17},
{'name':'Zebra Finch','life':17},
{'name':'Binturong','life':18},
{'name':'Blackbird','life':18},
{'name':'Budgerigar','life':18},
{'name':'Bull Snake','life':18},
{'name':'Hog','life':18},
{'name':'Pheasant','life':18},
{'name':'Turkey Buzzard','life':18},
{'name':'Wolf','life':18},
{'name':'Canvasback Duck','life':19},
{'name':'Beaver','life':20},
{'name':'Bottlenose Dolphin','life':20},
{'name':'Canary','life':20},
{'name':'Chinchilla','life':20},
{'name':'Eclectus Parrot','life':20},
{'name':'Gorilla','life':20},
{'name':'Grey Squirrel','life':20},
{'name':'Mallard','life':20},
{'name':'Mountain Lion','life':20},
{'name':'Ox','life':20},
{'name':'Pea Fowl','life':20},
{'name':'Polar Bear','life':20},
{'name':'Porcupine','life':20},
{'name':'Teal','life':20},
{'name':'Yak','life':20},
{'name':'Cottonmouth Mocassin','life':21},
{'name':'Cow','life':22},
{'name':'Dog','life':22},
{'name':'Elk','life':22},
{'name':'Rattlesnake','life':22},
{'name':'Tiger','life':22},
{'name':'Boa Constrictor','life':23},
{'name':'English Sparrow','life':23},
{'name':'Rat Snake','life':23},
{'name':'Bat','life':24},
{'name':'Cat','life':25},
{'name':'Conure','life':25},
{'name':'Pig (wild)','life':25},
{'name':'Domestic Pigeon','life':26},
{'name':'Galah','life':26},
{'name':'Congo Eel','life':27},
{'name':'Bull','life':28},
{'name':'Caiman','life':28},
{'name':'Cobra','life':28},
{'name':'Egyptian Goose','life':28},
{'name':'Hellbender','life':29},
{'name':'Bison','life':30},
{'name':'Tapir','life':30},
{'name':'Vultures','life':30},
{'name':'Cockatiel','life':32},
{'name':'Grizzly bear','life':32},
{'name':'Canada Goose','life':33},
{'name':'Trumpeter Swan','life':33},
{'name':'Deer','life':35},
{'name':'Lion','life':35},
{'name':'Superb Parrot','life':36},
{'name':'Toad','life':36},
{'name':'Asian elephant','life':40},
{'name':'Bare Eyed Cockatoo','life':40},
{'name':'Bear','life':40},
{'name':'Chimpanzee','life':40},
{'name':'Horse','life':40},
{'name':'Rhinoceros','life':40},
{'name':'Sulphur Crested Cockatoo','life':40},
{'name':'Crocodile','life':45},
{'name':'Donkey','life':45},
{'name':'Hippopotamus','life':45},
{'name':'African Grey Parrot','life':50},
{'name':'Camel','life':50},
{'name':'Macaw','life':50},
{'name':'Eagle','life':55},
{'name':'Eel','life':55},
{'name':'Giant Salamander','life':55},
{'name':'American Alligator','life':56},
{'name':'Snapping Turtle','life':57},
{'name':'Catfish','life':60},
{'name':'Alligator','life':68},
{'name':'Great Horned Owl','life':68},
{'name':'Elephant','life':70},
{'name':'Amazon Parrot','life':80},
{'name':'Parrot','life':80},
{'name':'Carp','life':100},
{'name':'American Box Turtle','life':123},
{'name':'Box Turtle','life':123},
{'name':'Giant Tortoise','life':152},
{'name':'Galapagos Land Tortoise','life':193},
{'name':'Greenland Shark','life':500},
]